version: "3"

services:
  django_blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000