# Generated by Django 3.0.1 on 2019-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Empty Header', max_length=50)),
                ('text', models.CharField(default='Empty Text', max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('publication_date', models.DateField()),
            ],
        ),
    ]
