# Generated by Django 3.0.1 on 2019-12-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits', models.IntegerField(default=0)),
                ('login', models.CharField(default='Stranger', max_length=100)),
            ],
        ),
    ]
